use prototipo_db;
insert into problemas values(1,'Dificuldades em estabelecer confiança entre os membros da equipe', 'Pessoas','');
insert into problemas values(2,'Falta de espírito de equipe', 'Pessoas','');
insert into problemas values(3,'Falta de comprometimento da equipe e dos stakeholders (usuários finais / clientes)', 'Pessoas','');
insert into problemas values(4,'Dificuldades em controlar a propriedade de código', 'Pessoas','');
insert into problemas values(5,'Falta de experiência da equipe', 'Pessoas','Novos integrantes da equipe sente dificuldades de entender o nicho do mercado, o negócio que a empresa atende.');
insert into problemas values(6,'Dificuldades em estabelecer um comum entendimento entre os membros da equipe que tenham diferentes experiências e culturas', 'Comunicação','');
insert into problemas values(7,'Dificuldades em se ter uma comunicação informal e de se estabelecer relações interpessoais entre os membros da equipe', 'Comunicação','');
insert into problemas values(8,'Dificuldades de se obter formas eficazes para se estabelecer uma comunicação', 'Comunicação','');
insert into problemas values(9,'Dificuldade em se obter feedback dos colegas da equipe sobre atividades de desenvolvimento em tempo hábil', 'Comunicação','');
insert into problemas values(10,'Dificuldade em se estabelecer um fluxo de troca de informações e de uma comunicação eficiente', 'Comunicação','');
insert into problemas values(11,'Dificuldade em se obter qualidade das informações comunicadas', 'Comunicação','');
insert into problemas values(12,'Dificuldade em gerenciar projetos distribuídos', 'Gerência','');
insert into problemas values(13,'Dificuldade em lidar com diferentes leis e políticas', 'Gerência','');
insert into problemas values(14,'Dificuldade em atribuir atividades a equipe de forma adequada', 'Gerência','');
insert into problemas values(15,'Dificuldade de planejar uma estimativa de esforço precisa', 'Gerência','');
insert into problemas values(16,'Dificuldades em obter-se um tempo viável de colaboração com colegas de outros países', 'Gerência','');
insert into problemas values(17,'Dificuldade em gerenciar expectativas internas e externas dentro do projeto', 'Gerência','');
insert into problemas values(18,'Dificuldades em estabelecer um eficiente gerenciamento de riscos', 'Gerência','');
insert into problemas values(19,'Dificuldades em documentar o software', 'Gerência','');
insert into problemas values(20,'Dificuldade na negociação de contrato com o cliente', 'Gerência','');
insert into problemas values(21,'Dificuldade de controlar a carga horária excessiva de trabalho', 'Gerência','');
insert into problemas values(22,'Falta de apoio à gestão', 'Gerência','');
insert into problemas values(23,'Dificuldade em ter um eficaz processo de engenharia de requisitos', 'Processos','');
insert into problemas values(24,'Dificuldade em definir e institucionalizar um processo unificado que abrange todo o ciclo de vida', 'Processos','');
insert into problemas values(25,'Dificuldade em definir uma arquitetura modular que diminuem a complexidade de coordenação', 'Processos','');
insert into problemas values(26,'Dificuldade do entendimento da complexidade dos sistemas de software', 'Processos','');
insert into problemas values(27,'Falta de ambiente e ferramentas adequadas para apoiar os métodos de engenharia de software', 'Infraestrutura e Tecnologia','');
insert into problemas values(28,'Falta de tecnologias de telecomunicações', 'Infraestrutura e Tecnologia','');
insert into problemas values(29,'Dificuldades em se projetar um software de fácil manutenção', 'Codificação','');
insert into problemas values(30,'Uso inadequado de técnicas de programação', 'Codificação','');
insert into problemas values(31,'Falta de padrões de codificação', 'Codificação','');
insert into problemas values(32,'Dificuldades em realizar a integração do software', 'Codificação','');
insert into problemas values(33,'Dificuldades em obter-se segurança no software', 'Codificação','');
insert into problemas values(34,'Dificuldade em documentar o software', 'Codificação','');
insert into problemas values(35,'Falta de testes no software', 'Codificação','');
